moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.12.5
project:
  name: zyflow
  mode: personal
  description: ''
  created_at: '2026-01-26 23:16:17'
  optimized: false
  template_version: 1.12.5
